// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuF7WRq4LHV_rHSKpeT4Y8tvQVFlQakNk',
    appId: '1:804848892826:web:b8420a04c79de5fde2d823',
    messagingSenderId: '804848892826',
    projectId: 'cinefy-d5223',
    authDomain: 'cinefy-d5223.firebaseapp.com',
    storageBucket: 'cinefy-d5223.firebasestorage.app',
    measurementId: 'G-4GJNHHCTLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-pW650CosXZP0_ovzV7TKPx_WHblUT0',
    appId: '1:804848892826:android:41c1463a4ed0fe23e2d823',
    messagingSenderId: '804848892826',
    projectId: 'cinefy-d5223',
    storageBucket: 'cinefy-d5223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBiS5wXKLagtbeRDKQLczXyx_WRErj9M',
    appId: '1:804848892826:ios:2b125ce0ba4c5b85e2d823',
    messagingSenderId: '804848892826',
    projectId: 'cinefy-d5223',
    storageBucket: 'cinefy-d5223.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiBiS5wXKLagtbeRDKQLczXyx_WRErj9M',
    appId: '1:804848892826:ios:2b125ce0ba4c5b85e2d823',
    messagingSenderId: '804848892826',
    projectId: 'cinefy-d5223',
    storageBucket: 'cinefy-d5223.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuF7WRq4LHV_rHSKpeT4Y8tvQVFlQakNk',
    appId: '1:804848892826:web:04158997f5f26b35e2d823',
    messagingSenderId: '804848892826',
    projectId: 'cinefy-d5223',
    authDomain: 'cinefy-d5223.firebaseapp.com',
    storageBucket: 'cinefy-d5223.firebasestorage.app',
    measurementId: 'G-2W89SK66F7',
  );
}
